name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      
      - name: Testing
        run: mvn clean test
